name: CI

on:
  push:
    branches: ["main", "fix_tests"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          repo-token: ${{ secrets.TOKEN }}
    - name: main
      run: make    
    - name: unit tests
      run: make test
    - name: run unit tests
      run: ./unit_tests
