name: CI

on:
  push:
    branches: ["main", "CI", "CI_draft"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make    
    - name: make test
      run: make test
    - name: run test
    - uses: parasoft/run-cpptest-action@1.0.1
    - name: test
      run: ./unit_tests
