name: CI

on:
  push:
    branches: ["main", "CI", "CI_draft"]
  pull_request:
    branches: ["main", "CI", "CI_draft"]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: main
      run: make    
    - name: unit tests
      run: make test
    - name: run unit tests
      run: ./unit_tests
