name: CI

on:
  push:
    branches: ["main", "CI", "CI_draft"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: eWaterCycle/setup-grpc@v5
      with:
        grpc-version: 1.30.2
    - name: make
      run: make    
    - name: make test
      run: make test
    - name: test
      run: ./unit_tests
